version: 2.1
orbs:
  go: circleci/go@1.7.1
workflows:
  main:
    jobs:
      - build

jobs:
  build:
    executor: 
      name: go/default
      tag: '1.18'
    working_directory: /home/circleci/go/src/github.com/ahoy-cli/ahoy
    steps:
      - checkout
      - run: git clone https://github.com/bats-core/bats-core.git && cd bats-core && sudo ./install.sh /usr/local && bats --version && cd -
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
      # - run: sudo apt search php
      # - run: sudo apt install php
      - run: |
          pwd
          ls -al
          ls -al /home/circleci/go/src/github.com
          ls -al /home/circleci/go/src/github.com/ahoy-cli/ahoy
      - go/load-cache
      - go/mod-download
      - run: go get -u golang.org/x/lint/golint
      - run: go mod vendor
      - go/save-cache
      - run: bash build.sh -v
      # - run: |
      #     env
      #     echo $GOPATH
      #     /home/circleci/go/bin/golangci-lint run
      - run: ./ahoy test
      - go/test
